/**
 * MindBase MCP Server - Conversation Tools
 *
 * Tool implementations for conversation management
 */

import type { StorageBackend, ConversationItem, QueryFilters, HybridSearchOptions, TimelineOptions, TopicGroup } from '../storage/interface.js';

export class ConversationTools {
  private currentSessionId?: string;

  constructor(private storage: StorageBackend) {}

  /**
   * Set current session ID for context
   */
  setCurrentSession(sessionId: string | undefined) {
    this.currentSessionId = sessionId;
  }

  /**
   * conversation_save - Save conversation with automatic embedding
   */
  async conversationSave(args: {
    source: string;
    title: string;
    content: any;
    metadata?: Record<string, any>;
    category?: string;
    priority?: string;
    channel?: string;
    sessionId?: string;
  }): Promise<{ id: string; createdAt: string }> {
    const item: ConversationItem = {
      id: '', // Will be generated by storage
      sessionId: args.sessionId || this.currentSessionId,
      source: args.source as any,
      title: args.title,
      content: args.content,
      metadata: args.metadata || {},
      category: args.category as any,
      priority: args.priority as any,
      channel: args.channel,
      createdAt: new Date(),
      updatedAt: new Date(),
    };

    const id = await this.storage.save(item);
    return {
      id,
      createdAt: item.createdAt.toISOString(),
    };
  }

  /**
   * conversation_get - Retrieve conversations with filtering
   */
  async conversationGet(args: {
    id?: string;
    source?: string;
    category?: string;
    priority?: string;
    channel?: string;
    sessionId?: string;
    limit?: number;
    offset?: number;
    createdAfter?: string;
    createdBefore?: string;
  }): Promise<{
    items: any[];
    total: number;
    hasMore: boolean;
  }> {
    // If ID is provided, get single item
    if (args.id) {
      const item = await this.storage.getById(args.id);
      if (!item) {
        return { items: [], total: 0, hasMore: false };
      }
      return {
        items: [this.formatItem(item)],
        total: 1,
        hasMore: false,
      };
    }

    // Otherwise, get with filters
    const filters: QueryFilters = {
      source: args.source,
      category: args.category,
      priority: args.priority,
      channel: args.channel,
      sessionId: args.sessionId || this.currentSessionId,
      limit: args.limit || 100,
      offset: args.offset || 0,
      createdAfter: args.createdAfter ? new Date(args.createdAfter) : undefined,
      createdBefore: args.createdBefore ? new Date(args.createdBefore) : undefined,
    };

    // Get items and count in parallel
    const { limit, offset, ...countFilters } = filters;
    const [items, total] = await Promise.all([
      this.storage.get(filters),
      this.storage.count(countFilters),
    ]);
    const hasMore = (offset || 0) + items.length < total;

    return {
      items: items.map(this.formatItem),
      total,
      hasMore,
    };
  }

  /**
   * conversation_search - Semantic search across conversations with recency ranking
   */
  async conversationSearch(args: {
    query: string;
    threshold?: number;
    limit?: number;
    source?: string;
    recencyWeight?: number;
    recencyTauSeconds?: number;
    recencyBoostDays?: number;
    recencyBoostValue?: number;
  }): Promise<{
    items: any[];
    query: string;
    weights: { semantic: number; recency: number };
  }> {
    const threshold = args.threshold ?? 0.7;
    const limit = args.limit ?? 10;
    const recencyWeight = args.recencyWeight ?? 0.15;

    const results = await this.storage.semanticSearch(
      args.query,
      limit,
      threshold,
      recencyWeight,
      args.recencyTauSeconds ?? 1209600,
      args.recencyBoostDays ?? 3,
      args.recencyBoostValue ?? 0.05
    );

    // Filter by source if specified
    let filteredResults = results;
    if (args.source) {
      filteredResults = results.filter((r) => r.item.source === args.source);
    }

    return {
      items: filteredResults.map((result) => ({
        ...this.formatItem(result.item),
        similarity: result.similarity,
        semanticScore: result.semanticScore,
        recencyScore: result.recencyScore,
        combinedScore: result.combinedScore,
      })),
      query: args.query,
      weights: {
        semantic: 1 - recencyWeight,
        recency: recencyWeight,
      },
    };
  }

  /**
   * conversation_hybrid_search - Hybrid search combining keyword, semantic, and recency
   *
   * Weights are normalized to sum to 1.0 automatically.
   */
  async conversationHybridSearch(args: {
    query: string;
    keywordWeight?: number;
    semanticWeight?: number;
    recencyWeight?: number;
    threshold?: number;
    limit?: number;
    source?: string;
    recencyTauSeconds?: number;
    recencyBoostDays?: number;
    recencyBoostValue?: number;
  }): Promise<{
    items: any[];
    query: string;
    weights: { keyword: number; semantic: number; recency: number };
  }> {
    const options: HybridSearchOptions = {
      keywordWeight: args.keywordWeight ?? 0.30,
      semanticWeight: args.semanticWeight ?? 0.55,
      recencyWeight: args.recencyWeight ?? 0.15,
      threshold: args.threshold ?? 0.6,
      limit: args.limit ?? 10,
      recencyTauSeconds: args.recencyTauSeconds ?? 1209600,
      recencyBoostDays: args.recencyBoostDays ?? 3,
      recencyBoostValue: args.recencyBoostValue ?? 0.05,
    };

    const results = await this.storage.hybridSearch(args.query, options);

    // Filter by source if specified
    let filteredResults = results;
    if (args.source) {
      filteredResults = results.filter((r) => r.item.source === args.source);
    }

    // Calculate normalized weights for response
    const kw = options.keywordWeight!;
    const sw = options.semanticWeight!;
    const rw = options.recencyWeight!;
    const sum = kw + sw + rw;

    return {
      items: filteredResults.map((result) => ({
        ...this.formatItem(result.item),
        keywordScore: result.keywordScore,
        semanticScore: result.semanticScore,
        recencyScore: result.recencyScore,
        combinedScore: result.combinedScore,
      })),
      query: args.query,
      weights: {
        keyword: kw / sum,
        semantic: sw / sum,
        recency: rw / sum,
      },
    };
  }

  /**
   * conversation_delete - Delete conversation by ID
   */
  async conversationDelete(args: { id: string }): Promise<{ success: boolean; deletedId?: string }> {
    const success = await this.storage.delete(args.id);
    return {
      success,
      deletedId: success ? args.id : undefined,
    };
  }

  /**
   * session_create - Create new session
   */
  async sessionCreate(args: {
    name: string;
    description?: string;
    parentId?: string;
  }): Promise<{ id: string; name: string; createdAt: string }> {
    const id = await this.storage.createSession(args.name, args.description, args.parentId);
    const session = await this.storage.getSession(id);

    if (!session) {
      throw new Error('Failed to retrieve created session');
    }

    return {
      id: session.id,
      name: session.name,
      createdAt: session.createdAt.toISOString(),
    };
  }

  /**
   * session_start - Start or resume a session
   */
  async sessionStart(args: {
    sessionId?: string;
    name?: string;
    description?: string;
  }): Promise<{
    id: string;
    name: string;
    description?: string;
    itemCount: number;
    createdAt: string;
  }> {
    let sessionId = args.sessionId;

    // If no sessionId provided, create new session
    if (!sessionId && args.name) {
      sessionId = await this.storage.createSession(args.name, args.description);
    }

    if (!sessionId) {
      throw new Error('Either sessionId or name must be provided');
    }

    const session = await this.storage.getSession(sessionId);
    if (!session) {
      throw new Error(`Session not found: ${sessionId}`);
    }

    // Set as current session
    this.currentSessionId = session.id;

    return {
      id: session.id,
      name: session.name,
      description: session.description,
      itemCount: session.itemCount || 0,
      createdAt: session.createdAt.toISOString(),
    };
  }

  /**
   * session_list - List recent sessions
   */
  async sessionList(args?: { limit?: number }): Promise<{
    sessions: any[];
    total: number;
  }> {
    const limit = args?.limit || 10;
    const sessions = await this.storage.listSessions(limit);

    return {
      sessions: sessions.map((s) => ({
        id: s.id,
        name: s.name,
        description: s.description,
        parentId: s.parentId,
        itemCount: s.itemCount || 0,
        createdAt: s.createdAt.toISOString(),
        updatedAt: s.updatedAt.toISOString(),
      })),
      total: sessions.length,
    };
  }

  /**
   * session_delete - Delete a session
   */
  async sessionDelete(args: { id: string }): Promise<{ success: boolean; deletedId?: string }> {
    const success = await this.storage.deleteSession(args.id);

    // If deleted session was current, clear it
    if (success && this.currentSessionId === args.id) {
      this.currentSessionId = undefined;
    }

    return {
      success,
      deletedId: success ? args.id : undefined,
    };
  }

  /**
   * conversation_timeline - Cross-source chronological view
   */
  async conversationTimeline(args: {
    sources?: string[];
    project?: string;
    createdAfter?: string;
    createdBefore?: string;
    limit?: number;
    offset?: number;
  }): Promise<{
    entries: any[];
    total: number;
  }> {
    const options: TimelineOptions = {
      sources: args.sources,
      project: args.project,
      createdAfter: args.createdAfter ? new Date(args.createdAfter) : undefined,
      createdBefore: args.createdBefore ? new Date(args.createdBefore) : undefined,
      limit: args.limit || 50,
      offset: args.offset || 0,
    };

    const entries = await this.storage.getTimeline(options);
    const total = await this.storage.count({
      source: args.sources?.[0],
      createdAfter: options.createdAfter,
      createdBefore: options.createdBefore,
    });

    return {
      entries: entries.map((e) => ({
        id: e.id,
        source: e.source,
        title: e.title,
        project: e.project,
        messageCount: e.messageCount,
        topics: e.topics,
        createdAt: e.createdAt instanceof Date ? e.createdAt.toISOString() : e.createdAt,
        updatedAt: e.updatedAt instanceof Date ? e.updatedAt.toISOString() : e.updatedAt,
      })),
      total,
    };
  }

  /**
   * conversation_topics - Topic grouping across sources
   */
  async conversationTopics(args?: {
    limit?: number;
    minCount?: number;
  }): Promise<{
    topics: any[];
    total: number;
  }> {
    const limit = args?.limit || 20;
    const minCount = args?.minCount || 1;

    const topics = await this.storage.getTopics(limit, minCount);

    return {
      topics: topics.map((t) => ({
        topic: t.topic,
        conversationCount: t.conversationCount,
        sources: t.sources,
        latestAt: t.latestAt instanceof Date ? t.latestAt.toISOString() : t.latestAt,
        earliestAt: t.earliestAt instanceof Date ? t.earliestAt.toISOString() : t.earliestAt,
        conversationIds: t.conversationIds.slice(0, 10), // Limit IDs for readability
      })),
      total: topics.length,
    };
  }

  /**
   * content_generate - Generate article draft from conversation data
   */
  async contentGenerate(args: {
    topic: string;
    platform: 'qiita' | 'zenn' | 'note';
    conversationIds?: string[];
    style?: string;
  }): Promise<{
    title: string;
    content: string;
    platform: string;
    metadata: Record<string, any>;
  }> {
    // Gather source material from conversations
    let conversations: ConversationItem[] = [];

    if (args.conversationIds && args.conversationIds.length > 0) {
      // Fetch specified conversations
      for (const id of args.conversationIds) {
        const item = await this.storage.getById(id);
        if (item) conversations.push(item);
      }
    } else {
      // Search for relevant conversations by topic
      const results = await this.storage.semanticSearch(args.topic, 10, 0.5);
      conversations = results.map((r) => r.item);
    }

    if (conversations.length === 0) {
      throw new Error(`No conversations found for topic: ${args.topic}`);
    }

    // Extract key content from conversations
    const sourceContent = conversations.map((c) => {
      const messages = c.content?.messages || [];
      const keyMessages = messages
        .filter((m: any) => m.role === 'user' || m.role === 'assistant')
        .slice(0, 20) // Limit to first 20 messages per conversation
        .map((m: any) => `**${m.role}**: ${typeof m.content === 'string' ? m.content.substring(0, 500) : JSON.stringify(m.content).substring(0, 500)}`);

      return {
        title: c.title,
        source: c.source,
        date: c.createdAt instanceof Date ? c.createdAt.toISOString().split('T')[0] : String(c.createdAt).split('T')[0],
        messages: keyMessages,
      };
    });

    // Generate platform-specific article structure
    const article = this.generateArticleStructure(args.topic, args.platform, sourceContent, args.style);

    return {
      title: article.title,
      content: article.content,
      platform: args.platform,
      metadata: {
        sourceConversations: conversations.length,
        sourceIds: conversations.map((c) => c.id),
        generatedAt: new Date().toISOString(),
        style: args.style || 'technical',
      },
    };
  }

  /**
   * Generate article structure based on platform conventions
   */
  private generateArticleStructure(
    topic: string,
    platform: 'qiita' | 'zenn' | 'note',
    sources: any[],
    style?: string
  ): { title: string; content: string } {
    const conversationSummary = sources
      .map((s) => `### ${s.title} (${s.source}, ${s.date})\n\n${s.messages.join('\n\n')}`)
      .join('\n\n---\n\n');

    switch (platform) {
      case 'qiita': {
        const title = `${topic}`;
        const content = `---
title: "${topic}"
tags:
  - name: "AI"
  - name: "LLM"
  - name: "開発"
private: true
---

## はじめに

<!-- この記事は MindBase の会話データから自動生成されたドラフトです -->
<!-- ${sources.length}件の会話から構成 -->

## 背景

<!-- 以下の会話内容を元にセクションを構成してください -->

${conversationSummary}

## まとめ

<!-- 上記の会話内容をまとめてください -->
`;
        return { title, content };
      }

      case 'zenn': {
        const title = `${topic}`;
        const content = `---
title: "${topic}"
emoji: "🤖"
type: "tech"
topics: ["AI", "LLM", "開発"]
published: false
---

## はじめに

<!-- MindBase 自動生成ドラフト: ${sources.length}件の会話から -->

${conversationSummary}

## まとめ
`;
        return { title, content };
      }

      case 'note': {
        const title = `${topic}`;
        const content = `# ${topic}

<!-- MindBase 自動生成ドラフト: ${sources.length}件の会話から -->
<!-- Note向け: ストーリー性を重視した構成にしてください -->

${conversationSummary}

---

*この記事は複数のAI会話から自動的にドラフトが生成されました。*
`;
        return { title, content };
      }
    }
  }

  /**
   * Format conversation item for output
   */
  private formatItem(item: ConversationItem): any {
    return {
      id: item.id,
      sessionId: item.sessionId,
      source: item.source,
      title: item.title,
      content: item.content,
      metadata: item.metadata,
      category: item.category,
      priority: item.priority,
      channel: item.channel,
      createdAt: item.createdAt.toISOString(),
      updatedAt: item.updatedAt.toISOString(),
    };
  }
}
